### ISSUE TITLE
Implement MVP features

### ISSUE THREAD

**Issue by mcobrien** [HubSpot/NioSmtpClient#1]
Initial features:

- [x] Close channels when `SmtpSessionFactory.close` is called
- [x] Accept `Collection<ByteBuf>` for message content and ensure they are [dot-stuffed](https://tools.ietf.org/html/rfc5321#section-4.5.2) and terminated. (sub issue: https://github.com/HubSpot/NioSmtpClient/issues/3 )
- [x] Detect timed-out connections
- [x] Implement keep-alive with NOOP
- [x] Support STARTTLS
- [x] Parse and expose supported authentication methods from the `EHLO` response
- [x] Support authenticating against remote servers
- [x] Support [8-bit MIME](https://tools.ietf.org/html/rfc6152)
- [x] Support [message size declaration](https://tools.ietf.org/html/rfc1870)

**Comment by axiak** [comment]
With regards to 8bitmime: I'm not actually sure how we should handle that. Theoretically we shouldn't be using mime/content-transfer-encoding headers **unless** we have 8BITMIME. in testing I just saw that the competitors to this library are just sending the email we sent along.

Perhaps we should allow the client to provide a different set of `Collection<ByteBuf>` and default to returning the same one?

**Comment by mcobrien** [comment]
Closing this issue now because each of the initial features are complete. 8bitmime is supported, although we'll use it properly as part of https://github.com/HubSpot/NioSmtpClient/issues/19.
