### ISSUE TITLE
Send messages in the most efficient way

### ISSUE THREAD

**Issue by mcobrien** [HubSpot/NioSmtpClient#19]
There are a number of different ESMTP extensions that affect how we submit messages to a remote server, and choosing which to use depends on the server and the message. It seems something like the following algorithm would be best:

1. if [chunking](https://tools.ietf.org/html/rfc1830) is supported, use that - everything can be 8 bit, and there's no dot stuffing required. We'll submit messages using the `BDAT` command instead of `DATA`. Gmail, icloud and outlook.com all support chunking.
2. If the client tells us the message only contains 7-bit characters, just use `DATA` and dot stuff as necessary according to the original SMTP spec. This will work everywhere.
3. If [8bitmime](https://tools.ietf.org/html/rfc6152) is supported, use that, applying the dot-stuffing algorithm. e.g. yahoo.com supports 8bitmime but not chunking.
4. If neither extension is supported, check if the message only contains 7-bit characters. If so, send it normally.
5. If we've detected the message contains 8 bit characters, but the server doesn't indicate support for chunking or 8bitmime, we'll need to parse the contents of the message and rewrite it 😞 using quoted-printable or base64. We should choose which encoding to use based on the number of non-7-bit characters (if the proportion is high, we should use base64).

@axiak, thoughts?

**Comment by axiak** [comment]
this sounds great :)

**Comment by axiak** [comment]
I'm not saying we should use this strategy, but MimeUtility uses a "majority-wins" rule: https://java.net/projects/javamail/sources/mercurial/content/mail/src/main/java/javax/mail/internet/MimeUtility.java?rev=469 (line 1440)

If you have to check for non ascii counts, you can use `CharMatcher.ascii().negate().countIn()`.

On second thought, you may have to do something that just looks byte-by-byte for bytes greater than 127. Might be a fast way to do that in netty with a bytebuf processor

**Comment by mcobrien** [comment]
The [description of quoted-printable](https://tools.ietf.org/html/rfc2045#section-6.7) in the MIME RFC describes which characters need to be encoded. I was thinking of counting those, then multiplying by two (because they're replaced with `=3D` or whatever) to get the quoted-printable overhead (actually the rules are a little more complicated, but that's a start). The base 64 overhead is 4 / 3 * message size, so quoted-printable is likely to win for emails using latin character sets.

It would be cool to examine an array of bytes as longs, and `&` them with `(1 << 7) | (1 << 15) | (1 << 23)...` but I'm not sure if/how that's possible in Java...

**Comment by axiak** [comment]
If you have a bytebuf, you can reset the reader index to 0 and use consecutive `readLong` commands. E.g. it would use https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/UnpooledUnsafeHeapByteBuf.java#L110 which will use Java's Unsafe object to access the long as you would expect in C.

**Comment by axiak** [comment]
also, I think we can solve the equation for the break-even point for qp size:

```
qp_size = qp_chars x 3 + (N - qp_chars)
qp_size = qp_chars x 2 + N
base_64_size = 4/3 x N

base_64 = qp_size
4/3 x N = qp_chars x 2 + N
1/3 x N = qp_chars x 2
1/6 x N = qp_chars
qp_chars / N = 1/6
```

So it seems to me that as soon as you find `qp_chars > N / 6`, you can short circuit and go base64.

**Comment by axiak** [comment]
(I'm now really curious why javax.mail decided the breakeven point was `N/2`, rather than `N/6`)

**Comment by mcobrien** [comment]
cool, thanks for this - seems like a nice opportunity to break out JMH :)
