### ISSUE TITLE
Support SMTPUTF8

### ISSUE THREAD

**Issue by axiak** [HubSpot/NioSmtpClient#2]
If the EHLO response includes the SMTPUTF8 extension, then we should be encoding/decoding responses in UTF8.

Right now our RequestEncoder and ResponseDecoder are using ASCII:

1) https://github.com/netty/netty/blob/4.1/codec-smtp/src/main/java/io/netty/handler/codec/smtp/SmtpRequestEncoder.java#L93
2) https://github.com/netty/netty/blob/4.1/codec-smtp/src/main/java/io/netty/handler/codec/smtp/SmtpResponseDecoder.java#L59

We should add an attribute to the `ChannelHandlerContext` to upgrade us to SMTPUTF8 if it's ready.

I would probably add a utility class to the SmtpCodec in netty proper to manage the toggling of the UTF8 feature. Then in this client turn it on or off depending on the response of EHLO

**Comment by mcobrien** [comment]
Fixed by https://github.com/HubSpot/NioSmtpClient/pull/66
