### ISSUE TITLE
High concurrent tests

### ISSUE THREAD

**Issue by axiak** [HubSpot/NioSmtpClient#24]
Just to expose potential race conditions, it might be nice to try a few operations pipelined and non pipelined sends with a lot of threads concurrently on the same connection.
It should send one after another without issue, but it's worth testing out.

**Comment by mcobrien** [comment]
What do you mean a lot of threads on the same connection? 

We currently have [a test that sends 100 emails concurrently](https://github.com/HubSpot/NioSmtpClient/blob/master/src/test/java/com/hubspot/smtp/IntegrationTest.java#L284-L301), though I could certainly change that to mix pipelined and non-pipelined transactions.

**Comment by axiak** [comment]
So two things:

1. Yes I think we should mix pipeline and non pipelined
2. I think we should initiate calls from a pool of threads to test visibility

**Comment by mcobrien** [comment]
Cool, makes sense. 

Apart from the initial connect, the test runs everything (i.e. sending each of the requests) in the default cached threadpool. Is it worth overriding that to e.g. a pool with 50 threads to ensure we're truly doing this concurrently? 

We could also run the connect calls in a pool, but that part is very quick and doesn't involve much state.

**Comment by mcobrien** [comment]
How's https://github.com/HubSpot/NioSmtpClient/pull/23/commits/8bbea7d5a39385f2e241e140da94ab3e1fe6a94b ?

**Comment by mcobrien** [comment]
Closing for now as the [integration tests](https://github.com/HubSpot/NioSmtpClient/blob/master/src/test/java/com/hubspot/smtp/IntegrationTest.java) cover this.
