### ISSUE TITLE
SmtpMessage object format

### ISSUE THREAD

**Issue by axiak** [HubSpot/NioSmtpClient#3]
Thinking about this a bit, I think the "proper" way to handle an SmtpMessage object would be an interface such as the example in niosmtp. That being said, looking at the array of object types we have at our disposal in Netty, I think the best one is `ChunkedInput<ByteBuf>`. So the interface would look like:

```java
public interface SmtpMessageContent {
  ChunkedInput<ByteBuf> get8BitMime();

  default ChunkedInput<ByteBuf> get7BitFallback() {
    return get8BitMime();
  }
}
```

In this way we can potentially build code to extract the plain text version of the email and strip non-ascii characters in the event we really need to send 7-bit emails. (Though this is still something we need to investigate.)

The nice thing about using ChunkedInput, is that a user of the API can define that in several ways. 
They could do this:

```java
public class SmtpMessageFileContent {
  private final File file;

  public SmtpMessageFileContent(File file) {
    this.file = file;
  }

  @Override
  public ChunkedInput<ByteBuf> get8BitMime() {
    return new ChunkedNioFile(file);
  }
}
```

The only sticking point with this interface is that due to the contract of `ChunkedInput` we'll want to call `release()` on the bytebufs we are given. This is okay as long as we make sure that when we implement ChunkedInput from bytebufs we are allocating them properly. E.g.:

```java
public class ByteArraySmtpMessageContent {
  private final List<ByteBuf> byteBufs;

  @Override
  public ChunkedInput<ByteBuf> get8BitMime() {
    return new ChunkedInput<>() {
      Iterator<ByteBuf> it = byteBufs.iterator();
      // boilerplate elided
      public ByteBuf readChunk(ChannelHandlerContext ctx) {
         ByteBuf next = it.next();
         next.retain(); // yay ref-counting
         return next;
      }
    };
  }
}
```

**Comment by mcobrien** [comment]
Looking at this in more detail, I'm not sure `ChunkedInput` is what we want. Chunks are returned by calling `readChunk` which can block depending on the implementation (see for example, [this comment](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/stream/ChunkedStream.java#L32-L33) in `ChunkedStream`).

Chunking might be useful later if we want to support very large emails without running out of memory, but for now it might be simpler to just require `ByteBuf` contents. These can be `CompositeByteBuf` instances so clients won't need to allocate a single contiguous block of memory, but we do get the assurance that everything is to process and send without blocking. 

Thoughts, @axiak?

```
public interface SmtpMessageContent {
  ByteBuf get8BitMime();

  default ByteBuf get7BitFallback() {
    return get8BitMime();
  }
}
```

**Comment by axiak** [comment]
for the MVP we'll need to support some support for chunks - we already have emails too large to keep in contiguous blocks of memory.

I think for the MVP it's fine not worrying about the potential for blocking and put a TODO or something that we'll have to feed that data from a thread.

**Comment by mcobrien** [comment]
Just by using `ByteBuf` though we can support chunks and avoid contiguous blocks - we don't need to use `ChunkedInput`.

e.g.

```
List<byte[]> messageChunks = // ...
ByteBuf composite = Unpooled.wrappedBuffer(messageChunks.toArray(new byte[0][]));
```

**Comment by axiak** [comment]
OK, sounds good for an MVP then :)

**Comment by axiak** [comment]
Btw be sure to call `.retain()` before sending the bytebufs to channel.write: https://github.com/netty/netty/issues/1482

**Comment by axiak** [comment]
How about this?

```java
public interface SmtpMessageContent {
  int size();
  Object get8BitMimeEncodedContent();
  default Object get7BitEncodedContent() {
    return get8BitMimeEncodedContent();
  }
} 

```

**Comment by mcobrien** [comment]
Closed by https://github.com/HubSpot/NioSmtpClient/pull/9
