### ISSUE TITLE
Where's the SmtpSessionConfig class

### ISSUE THREAD

**Issue by akkascala** [HubSpot/NioSmtpClient#69]
Compile fail.In AbstractSmtpSessionConfig class, can't find SmtpSessionConfig Class.

**Comment by mcobrien** [comment]
Hey, the `SmtpSessionConfig` class is generated from `AbstractSmtpSessionConfig` by [Immutables](https://immutables.github.io/). This should happen automatically if you build with Maven.

The build is passing here: https://travis-ci.org/HubSpot/NioSmtpClient.
