### ISSUE TITLE
NioSmtpClient  artifact is not available in public maven repo

### ISSUE THREAD

**Issue by rafalgorzkowski** [HubSpot/NioSmtpClient#71]
Hi,

Do you consider uploading the artifact to any public maven repo?

**Comment by jhaber** [comment]
This should just be a matter of cutting a release and publishing to Maven central, thoughts on doing that @mcobrien @axiak ?

**Comment by mcobrien** [comment]
@rafalgorzkowski thanks for the suggestion! The latest version is now available at https://search.maven.org/artifact/com.hubspot/NioSmtpClient/1.1.0/jar.

**Comment by rafalgorzkowski** [comment]
Thank you!
